-- MySQL Script generated by MySQL Workbench
-- Mon Jul 17 21:49:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema languages
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema languages
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `languages` DEFAULT CHARACTER SET utf8 ;
USE `languages` ;

-- -----------------------------------------------------
-- Table `languages`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `languages`.`language` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `creator` VARCHAR(255) NULL,
  `current_version` DOUBLE NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
