-- MySQL Script generated by MySQL Workbench
-- Tue Jul 18 16:46:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema relationship
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema relationship
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `relationship` DEFAULT CHARACTER SET utf8 ;
USE `relationship` ;

-- -----------------------------------------------------
-- Table `relationship`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relationship`.`persons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relationship`.`licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relationship`.`licence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `exp_date` DATETIME NULL,
  `state` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `persons_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_licence_persons_idx` (`persons_id` ASC),
  CONSTRAINT `fk_licence_persons`
    FOREIGN KEY (`persons_id`)
    REFERENCES `relationship`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
